name: Build
on:
  push:
    branches:
      - master

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile LaTex
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: main.tex
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
